# Base configs
#baseurl: "https://photo.garrettgu.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Garrett Gu Photography"
subtitle: ""
author: "Garrett Gu"
header:
 title: "Photography"
 subtitle: "by Garrett Gu"
footer:
 name: "Hey there, my name is Garrett. This is my photography portfolio"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/garrettgu10"
